# Generated by Django 4.0.2 on 2022-04-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
