# Generated by Django 4.0.2 on 2022-04-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_remove_tag_content_type_remove_tag_object_id'),
        ('recipes', '0002_alter_recipe_category_alter_recipe_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
    ]
